version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ignite
    expose:
      - 5432
    ports:
      - 5433:5432