// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"main/ent/coffee"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (c *CoffeeQuery) CollectFields(ctx context.Context, satisfies ...string) (*CoffeeQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return c, nil
	}
	if err := c.collectField(ctx, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return c, nil
}

func (c *CoffeeQuery) collectField(ctx context.Context, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(coffee.Columns))
		selectedFields = []string{coffee.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "sugar":
			if _, ok := fieldSeen[coffee.FieldSugar]; !ok {
				selectedFields = append(selectedFields, coffee.FieldSugar)
				fieldSeen[coffee.FieldSugar] = struct{}{}
			}
		case "coffee":
			if _, ok := fieldSeen[coffee.FieldCoffee]; !ok {
				selectedFields = append(selectedFields, coffee.FieldCoffee)
				fieldSeen[coffee.FieldCoffee] = struct{}{}
			}
		case "powderedMilk":
			if _, ok := fieldSeen[coffee.FieldPowderedMilk]; !ok {
				selectedFields = append(selectedFields, coffee.FieldPowderedMilk)
				fieldSeen[coffee.FieldPowderedMilk] = struct{}{}
			}
		case "coffeeMate":
			if _, ok := fieldSeen[coffee.FieldCoffeeMate]; !ok {
				selectedFields = append(selectedFields, coffee.FieldCoffeeMate)
				fieldSeen[coffee.FieldCoffeeMate] = struct{}{}
			}
		case "milk":
			if _, ok := fieldSeen[coffee.FieldMilk]; !ok {
				selectedFields = append(selectedFields, coffee.FieldMilk)
				fieldSeen[coffee.FieldMilk] = struct{}{}
			}
		case "water":
			if _, ok := fieldSeen[coffee.FieldWater]; !ok {
				selectedFields = append(selectedFields, coffee.FieldWater)
				fieldSeen[coffee.FieldWater] = struct{}{}
			}
		case "rating":
			if _, ok := fieldSeen[coffee.FieldRating]; !ok {
				selectedFields = append(selectedFields, coffee.FieldRating)
				fieldSeen[coffee.FieldRating] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		c.Select(selectedFields...)
	}
	return nil
}

type coffeePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CoffeePaginateOption
}

func newCoffeePaginateArgs(rv map[string]any) *coffeePaginateArgs {
	args := &coffeePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

func limitRows(partitionBy string, limit int, orderBy ...sql.Querier) func(s *sql.Selector) {
	return func(s *sql.Selector) {
		d := sql.Dialect(s.Dialect())
		s.SetDistinct(false)
		with := d.With("src_query").
			As(s.Clone()).
			With("limited_query").
			As(
				d.Select("*").
					AppendSelectExprAs(
						sql.RowNumber().PartitionBy(partitionBy).OrderExpr(orderBy...),
						"row_number",
					).
					From(d.Table("src_query")),
			)
		t := d.Table("limited_query").As(s.TableName())
		*s = *d.Select(s.UnqualifiedColumns()...).
			From(t).
			Where(sql.LTE(t.C("row_number"), limit)).
			Prefix(with)
	}
}

// mayAddCondition appends another type condition to the satisfies list
// if condition is enabled (Node/Nodes) and it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond string) []string {
	if len(satisfies) == 0 {
		return satisfies
	}
	for _, s := range satisfies {
		if typeCond == s {
			return satisfies
		}
	}
	return append(satisfies, typeCond)
}
