// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"main/ent/coffee"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// CoffeeEdge is the edge representation of Coffee.
type CoffeeEdge struct {
	Node   *Coffee `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// CoffeeConnection is the connection containing edges to Coffee.
type CoffeeConnection struct {
	Edges      []*CoffeeEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *CoffeeConnection) build(nodes []*Coffee, pager *coffeePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Coffee
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Coffee {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Coffee {
			return nodes[i]
		}
	}
	c.Edges = make([]*CoffeeEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &CoffeeEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// CoffeePaginateOption enables pagination customization.
type CoffeePaginateOption func(*coffeePager) error

// WithCoffeeOrder configures pagination ordering.
func WithCoffeeOrder(order *CoffeeOrder) CoffeePaginateOption {
	if order == nil {
		order = DefaultCoffeeOrder
	}
	o := *order
	return func(pager *coffeePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultCoffeeOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithCoffeeFilter configures pagination filter.
func WithCoffeeFilter(filter func(*CoffeeQuery) (*CoffeeQuery, error)) CoffeePaginateOption {
	return func(pager *coffeePager) error {
		if filter == nil {
			return errors.New("CoffeeQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type coffeePager struct {
	reverse bool
	order   *CoffeeOrder
	filter  func(*CoffeeQuery) (*CoffeeQuery, error)
}

func newCoffeePager(opts []CoffeePaginateOption, reverse bool) (*coffeePager, error) {
	pager := &coffeePager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultCoffeeOrder
	}
	return pager, nil
}

func (p *coffeePager) applyFilter(query *CoffeeQuery) (*CoffeeQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *coffeePager) toCursor(c *Coffee) Cursor {
	return p.order.Field.toCursor(c)
}

func (p *coffeePager) applyCursors(query *CoffeeQuery, after, before *Cursor) (*CoffeeQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultCoffeeOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *coffeePager) applyOrder(query *CoffeeQuery) *CoffeeQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultCoffeeOrder.Field {
		query = query.Order(DefaultCoffeeOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *coffeePager) orderExpr(query *CoffeeQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultCoffeeOrder.Field {
			b.Comma().Ident(DefaultCoffeeOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Coffee.
func (c *CoffeeQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...CoffeePaginateOption,
) (*CoffeeConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newCoffeePager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if c, err = pager.applyFilter(c); err != nil {
		return nil, err
	}
	conn := &CoffeeConnection{Edges: []*CoffeeEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = c.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if c, err = pager.applyCursors(c, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		c.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := c.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	c = pager.applyOrder(c)
	nodes, err := c.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// CoffeeOrderField defines the ordering field of Coffee.
type CoffeeOrderField struct {
	// Value extracts the ordering value from the given Coffee.
	Value    func(*Coffee) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) coffee.OrderOption
	toCursor func(*Coffee) Cursor
}

// CoffeeOrder defines the ordering of Coffee.
type CoffeeOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *CoffeeOrderField `json:"field"`
}

// DefaultCoffeeOrder is the default ordering of Coffee.
var DefaultCoffeeOrder = &CoffeeOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &CoffeeOrderField{
		Value: func(c *Coffee) (ent.Value, error) {
			return c.ID, nil
		},
		column: coffee.FieldID,
		toTerm: coffee.ByID,
		toCursor: func(c *Coffee) Cursor {
			return Cursor{ID: c.ID}
		},
	},
}

// ToEdge converts Coffee into CoffeeEdge.
func (c *Coffee) ToEdge(order *CoffeeOrder) *CoffeeEdge {
	if order == nil {
		order = DefaultCoffeeOrder
	}
	return &CoffeeEdge{
		Node:   c,
		Cursor: order.Field.toCursor(c),
	}
}
